baseURL = "https://library.starrypoint.me"
title = "Northstar Public Library"
author = "Whistler SAI"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "vnovel"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = ""

# Disqus Comment System
#disqusShortname = ""

[params]
# The number of articles to be displayed on a single page.
paginator_pages = "9"

# Site logo.
#logo = ""

  [params.homepage_meta_tags]
    meta_description = "The NPL's Whistler SAI archives."
    meta_og_title = "Northstar Public Library"
    meta_og_type = "website"
    meta_og_url = "https://library.starrypoint.me"
    meta_og_image = "https://library.starrypoint.me/img/setup.png"
    meta_og_description = "The NPL's Whistler SAI archives."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "https://library.starrypoint.me"
    meta_twitter_creator = ""


[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "https://starrypoint.me"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
    
